"""
Bethesda engine plugin — covers Starfield, Skyrim SE, Fallout 4.
Capabilities: load order, script extender, activation toggle.
"""

import logging
import shutil
import stat
from pathlib import Path


from lsmm.engines.base import BaseEngine
from lsmm.core.config import GamePaths
from lsmm.core.script_extender import ScriptExtenderManager
from lsmm.core.plugins import PluginsFile
from lsmm.core.staging import (
    deploy_mod,
    get_mod_staging_dir,
    remove_staged_mod,
    stage_mod,
    undeploy_mod,
)
from lsmm.core.installer import (
    DLL_EXTENSION,
    PLUGIN_EXTENSIONS,
    ConflictError,
    cache_archive,
    check_conflicts,
    check_conflicts_fomod,
    detect_and_install,
    extract,
    install_fomod_files,
    load_manifest,
    record_install,
    remove_from_manifest,
    temp_extract_dir,
)

logger = logging.getLogger(__name__)

LAUNCH_SCRIPT_CONTENT = """\
#!/bin/bash
# Generated by linux-mod-manager
# Replaces the game exe with the script extender loader in Steam's Proton command.
new_args=()
next_is_exe=false
for arg in "$@"; do
    if $next_is_exe; then
        new_args+=("${{arg%/*}}/{loader_exe}")
        next_is_exe=false
    else
        new_args+=("$arg")
        [[ "$arg" == "waitforexitandrun" ]] && next_is_exe=true
    fi
done
exec "${{new_args[@]}}"
"""


class BethesdaEngine(BaseEngine):
    has_load_order = True
    has_script_extender = True
    has_activation_toggle = True
    supports_staging = True

    def __init__(self, profile: dict):
        super().__init__(profile)
        self.paths = GamePaths(profile)
        se_profile = profile.get("script_extender", {})
        self._se_manager = ScriptExtenderManager(
            se_profile, self.paths.game_root, profile.get("slug", "")
        ) if se_profile else None

    # ── Install ──────────────────────────────────────────────────────────────

    def install(
        self,
        archive_path: Path,
        mod_name: str | None = None,
        force: bool = False,
        nexus_meta: dict | None = None,
        fomod_files: list[tuple[str, str]] | None = None,
        staging: bool = False,
    ) -> None:
        """
        Install a mod archive. Raises ConflictError if the mod would overwrite
        files owned by another tracked mod — unless force=True.
        fomod_files: when provided, only these (src, dst) pairs are installed.
        nexus_meta: optional dict with keys game_domain, mod_id, file_id.
        staging: when True, extract to staging dir and deploy via symlinks.
        """
        name = mod_name or archive_path.stem
        game_slug = self.profile.get("slug")
        with temp_extract_dir() as tmp:
            logger.info(f"Extracting {archive_path.name}...")
            extract(archive_path, tmp)

            # SE archive: if the archive contains the SE loader, install to game_root
            se_cfg = self.profile.get("script_extender", {})
            se_loader_name = se_cfg.get("loader_exe")
            se_root = self._find_se_root(tmp, se_loader_name) if se_loader_name else None
            if se_root is not None:
                archive_cache = cache_archive(archive_path, game_slug)
                self.paths.game_root.mkdir(parents=True, exist_ok=True)
                installed = []
                for src in se_root.rglob("*"):
                    if not src.is_file():
                        continue
                    rel = src.relative_to(se_root)
                    dst = self.paths.game_root / rel
                    dst.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(src, dst)
                    installed.append(dst)
                record_install(name, archive_path, installed, game_slug=game_slug,
                               archive_cache=archive_cache, nexus_meta=nexus_meta)
                if nexus_meta and nexus_meta.get("version") and game_slug:
                    from lsmm.core.config import save_se_installed_version
                    save_se_installed_version(game_slug, nexus_meta["version"].lstrip("v"))
                logger.info(f"✓ Installed SE: {name}")
                return

            if fomod_files is not None:
                if not force:
                    conflicts = check_conflicts_fomod(fomod_files, self.paths.data_dir, load_manifest(), name)
                    if conflicts:
                        raise ConflictError(conflicts)
                archive_cache = cache_archive(archive_path, game_slug)
                logger.info("Installing FOMOD-selected files...")
                installed, backups = install_fomod_files(tmp, fomod_files, self.paths.data_dir, game_slug, name)
                staging_used = False
            elif staging:
                if not force:
                    conflicts = check_conflicts(tmp, self.paths.data_dir, load_manifest(), name)
                    if conflicts:
                        raise ConflictError(conflicts)
                archive_cache = cache_archive(archive_path, game_slug)
                logger.info("Staging files...")
                stage_mod(archive_path, game_slug, name)
                installed = deploy_mod(game_slug, name, self.paths.data_dir)
                backups = {}
                staging_used = True
            else:
                if not force:
                    conflicts = check_conflicts(tmp, self.paths.data_dir, load_manifest(), name)
                    if conflicts:
                        raise ConflictError(conflicts)
                archive_cache = cache_archive(archive_path, game_slug)
                logger.info("Installing files...")
                installed, backups = detect_and_install(tmp, self.paths.data_dir, game_slug, name)
                staging_used = False

            plugins_added = []
            plugins_file = PluginsFile.read(self.paths.plugins_txt)
            for dst in installed:
                if dst.suffix.lower() in PLUGIN_EXTENSIONS and dst.parent == self.paths.data_dir:
                    plugins_file.add(dst.name, active=True)
                    plugins_added.append(dst.name)
            plugins_file.write()

            staging_path = get_mod_staging_dir(game_slug, name) if staging_used else None
            record_install(name, archive_path, installed, game_slug=game_slug,
                           archive_cache=archive_cache, backups=backups,
                           nexus_meta=nexus_meta, staged=staging_used,
                           staging_path=staging_path)

            # If this install provided the SE loader, persist the version for display
            se_loader = getattr(self.paths, "se_loader", None)
            if se_loader and se_loader.exists() and nexus_meta:
                ver = nexus_meta.get("version", "")
                if ver and game_slug:
                    from lsmm.core.config import save_se_installed_version
                    save_se_installed_version(game_slug, ver.lstrip("v"))

        logger.info(f"✓ Installed: {name}")
        if plugins_added:
            logger.info(f"  Plugins activated: {', '.join(plugins_added)}")

    def _find_se_root(self, extracted: Path, loader_exe: str) -> Path | None:
        """Return the directory containing loader_exe inside extracted archive, or None."""
        for candidate in extracted.rglob(loader_exe):
            return candidate.parent
        return None

    # ── Uninstall ────────────────────────────────────────────────────────────

    def uninstall(self, mod_name: str) -> None:
        entry = load_manifest().get(mod_name)
        if not entry:
            # Untracked DLL in se_plugins_dir
            if self.paths.se_plugins_dir:
                candidate = self.paths.se_plugins_dir / f"{mod_name}{DLL_EXTENSION}"
                if candidate.exists():
                    candidate.unlink()
                    logger.info(f"✓ Removed untracked SE plugin: {candidate.name}")
                    return
            # Unmanaged plugin — mod_name IS the plugin filename (e.g. "MyMod.esp")
            plugin_file = self.paths.data_dir / mod_name
            if plugin_file.exists() and plugin_file.suffix.lower() in PLUGIN_EXTENSIONS:
                pf = PluginsFile.read(self.paths.plugins_txt)
                pf.remove(mod_name)
                pf.write()
                plugin_file.unlink()
                logger.info(f"✓ Removed unmanaged plugin: {mod_name}")
                return
            logger.warning(f"Not installed: {mod_name}")
            return

        plugins_file = PluginsFile.read(self.paths.plugins_txt)
        failed: list[str] = []

        if entry.get("staged"):
            game_slug = self.profile.get("slug")
            undeploy_mod(game_slug, mod_name, self.paths.data_dir)
            remove_staged_mod(game_slug, mod_name)
            for f_str in entry.get("files", []):
                f = Path(f_str)
                if f.suffix.lower() in PLUGIN_EXTENSIONS:
                    plugins_file.remove(f.name)
        else:
            backups = entry.get("backups", {})
            for f_str in entry.get("files", []):
                f = Path(f_str)
                bak_str = backups.get(f_str)
                try:
                    if bak_str:
                        bak = Path(bak_str)
                        if bak.exists():
                            f.parent.mkdir(parents=True, exist_ok=True)
                            shutil.copy2(bak, f)
                            bak.unlink()
                    else:
                        if f.exists():
                            f.unlink()
                except OSError as e:
                    logger.warning("Could not remove %s: %s", f, e)
                    failed.append(f_str)
                if f.suffix.lower() in PLUGIN_EXTENSIONS:
                    plugins_file.remove(f.name)
                # Clean empty parent dirs up to data_dir
                try:
                    parent = f.parent
                    while parent != self.paths.data_dir and parent.exists() and not any(parent.iterdir()):
                        parent.rmdir()
                        parent = parent.parent
                except Exception:
                    pass

        plugins_file.write()
        if failed:
            logger.warning("Partial uninstall of %s — %d file(s) not removed: %s",
                           mod_name, len(failed), failed)
        else:
            remove_from_manifest(mod_name)
            logger.info(f"✓ Uninstalled: {mod_name}")

    # ── List ─────────────────────────────────────────────────────────────────

    def list_mods(self) -> list[dict]:
        game_slug = self.profile.get("slug")
        manifest = load_manifest()
        plugin_lookup = {p.name: p for p in PluginsFile.read(self.paths.plugins_txt).plugins}
        result = []
        tracked_se_dlls: set[str] = set()
        tracked_plugin_names: set[str] = set()

        data_dir_str = str(self.paths.data_dir)

        for name, entry in manifest.items():
            entry_game = entry.get("game")
            if entry_game is not None and entry_game != game_slug:
                continue
            # Old entries without a game tag: check file paths to avoid
            # showing mods from other games (e.g. Starfield mods in Skyrim).
            if entry_game is None:
                files = entry.get("files", [])
                if files and not any(f.startswith(data_dir_str) for f in files):
                    continue
            files = entry.get("files", [])
            plugins = []
            for f in files:
                ext = Path(f).suffix.lower()
                if ext in PLUGIN_EXTENSIONS:
                    plugins.append(f)
                    tracked_plugin_names.add(Path(f).name)
                elif ext == DLL_EXTENSION:
                    tracked_se_dlls.add(Path(f).name)
            active = all(
                (p := plugin_lookup.get(Path(f).name)) and p.active
                for f in plugins
            ) if plugins else True
            result.append({
                "name": name, "active": active, "plugins": plugins,
                "kind": "mod", "nexus": entry.get("nexus"),
            })

        if self.paths.se_plugins_dir and self.paths.se_plugins_dir.exists():
            for dll in sorted(self.paths.se_plugins_dir.glob(f"*{DLL_EXTENSION}")):
                if dll.name not in tracked_se_dlls:
                    result.append({"name": dll.stem, "active": True, "plugins": [], "kind": "se_plugin"})

        # Plugins present in Plugins.txt but not tracked in the manifest
        # (installed before LSMM or via another tool)
        for p in plugin_lookup.values():
            if p.name not in tracked_plugin_names and (self.paths.data_dir / p.name).exists():
                result.append({
                    "name": p.name,
                    "active": p.active,
                    "plugins": [str(self.paths.data_dir / p.name)],
                    "kind": "unmanaged",
                })

        return result

    # ── Load order ───────────────────────────────────────────────────────────

    def get_load_order(self) -> list[str]:
        return PluginsFile.read(self.paths.plugins_txt).get_order()

    def set_load_order(self, order: list[str]) -> None:
        pf = PluginsFile.read(self.paths.plugins_txt)
        pf.set_order(order)
        pf.write()

    # ── Activation ───────────────────────────────────────────────────────────

    def enable_mod(self, mod_name: str) -> None:
        entry = load_manifest().get(mod_name, {})
        if entry.get("staged"):
            deploy_mod(self.profile.get("slug"), mod_name, self.paths.data_dir)
        self._set_mod_active(mod_name, True)

    def disable_mod(self, mod_name: str) -> None:
        entry = load_manifest().get(mod_name, {})
        if entry.get("staged"):
            undeploy_mod(self.profile.get("slug"), mod_name, self.paths.data_dir)
        self._set_mod_active(mod_name, False)

    def _set_mod_active(self, mod_name: str, active: bool) -> None:
        manifest = load_manifest()
        pf = PluginsFile.read(self.paths.plugins_txt)
        if mod_name not in manifest:
            # Unmanaged plugin: mod_name IS the plugin filename
            pf.set_active(mod_name, active)
            pf.write()
            return
        for f in manifest[mod_name].get("files", []):
            p = Path(f)
            if p.suffix.lower() in PLUGIN_EXTENSIONS:
                pf.set_active(p.name, active)
        pf.write()
        logger.info(f"✓ {'enabled' if active else 'disabled'}: {mod_name}")

    # ── Script extender setup ────────────────────────────────────────────────

    def setup_script_extender(self) -> None:
        se = self.profile.get("script_extender")
        if not se:
            logger.warning("No script extender configured for this game.")
            return

        script_path = self.paths.game_root / "se_launch.sh"
        script_path.write_text(
            LAUNCH_SCRIPT_CONTENT.format(loader_exe=se["loader_exe"])
        )
        script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC)

        logger.info(f"✓ Launch script created: {script_path}")
        logger.info("\nAdd this to Steam launch options:")
        logger.info(f'  "{script_path}" %command%')
        return script_path

    def get_se_installed_version(self) -> str | None:
        return self._se_manager.get_installed_version() if self._se_manager else None

    def get_se_latest_info(self) -> tuple[str, str, str] | None:
        return self._se_manager.get_latest_info() if self._se_manager else None

    def download_script_extender(self, on_progress=None) -> None:
        if not self._se_manager:
            raise RuntimeError("No script extender configured for this game")
        self._se_manager.download(on_progress=on_progress)

    def uninstall_script_extender(self) -> None:
        if not self._se_manager:
            raise RuntimeError("No script extender configured for this game")
        self._se_manager.uninstall()

    # ── INI setup ────────────────────────────────────────────────────────────

    def ensure_ini(self) -> None:
        ini = self.paths.custom_ini
        ini.parent.mkdir(parents=True, exist_ok=True)

        content = ini.read_text() if ini.exists() else ""
        if "bInvalidateOlderFiles=1" not in content:
            with ini.open("a") as f:
                f.write("\n[Archive]\nbInvalidateOlderFiles=1\nsResourceDataDirsFinal=\n")
            logger.info(f"✓ Updated: {ini}")
        else:
            logger.info(f"✓ INI already correct: {ini}")
