"""
Bethesda engine plugin — covers Starfield, Skyrim SE, Fallout 4.
Capabilities: load order, script extender, activation toggle.
"""

import shutil
import stat
from pathlib import Path


from lsmm.engines.base import BaseEngine
from lsmm.core.config import GamePaths
from lsmm.core.plugins import PluginsFile
from lsmm.core.installer import (
    DLL_EXTENSION,
    PLUGIN_EXTENSIONS,
    ConflictError,
    cache_archive,
    check_conflicts,
    detect_and_install,
    extract,
    load_manifest,
    record_install,
    remove_from_manifest,
    temp_extract_dir,
)

LAUNCH_SCRIPT_CONTENT = """\
#!/bin/bash
# Generated by linux-mod-manager
# Replaces the game exe with the script extender loader in Steam's Proton command.
exec "${{@/{game_exe}/{loader_exe}}}"
"""


class BethesdaEngine(BaseEngine):
    has_load_order = True
    has_script_extender = True
    has_activation_toggle = True

    def __init__(self, profile: dict):
        super().__init__(profile)
        self.paths = GamePaths(profile)

    # ── Install ──────────────────────────────────────────────────────────────

    def install(
        self,
        archive_path: Path,
        mod_name: str = None,
        force: bool = False,
        nexus_meta: dict | None = None,
    ) -> None:
        """
        Install a mod archive. Raises ConflictError if the mod would overwrite
        files owned by another tracked mod — unless force=True.
        nexus_meta: optional dict with keys game_domain, mod_id, file_id.
        """
        name = mod_name or archive_path.stem
        game_slug = self.profile.get("slug")
        with temp_extract_dir() as tmp:
            print(f"Extracting {archive_path.name}...")
            extract(archive_path, tmp)

            if not force:
                conflicts = check_conflicts(tmp, self.paths.data_dir, load_manifest(), name)
                if conflicts:
                    raise ConflictError(conflicts)

            archive_cache = cache_archive(archive_path, game_slug)

            print("Installing files...")
            installed, backups = detect_and_install(tmp, self.paths.data_dir, game_slug, name)

            plugins_added = []
            plugins_file = PluginsFile.read(self.paths.plugins_txt)
            for dst in installed:
                if dst.suffix.lower() in PLUGIN_EXTENSIONS and dst.parent == self.paths.data_dir:
                    plugins_file.add(dst.name, active=True)
                    plugins_added.append(dst.name)
            plugins_file.write()

            record_install(name, archive_path, installed, game_slug=game_slug,
                           archive_cache=archive_cache, backups=backups,
                           nexus_meta=nexus_meta)

        print(f"✓ Installed: {name}")
        if plugins_added:
            print(f"  Plugins activated: {', '.join(plugins_added)}")

    # ── Uninstall ────────────────────────────────────────────────────────────

    def uninstall(self, mod_name: str) -> None:
        entry = remove_from_manifest(mod_name)
        if not entry:
            print(f"Not installed: {mod_name}")
            return

        backups = entry.get("backups", {})
        plugins_file = PluginsFile.read(self.paths.plugins_txt)

        for f_str in entry.get("files", []):
            f = Path(f_str)
            bak_str = backups.get(f_str)
            if bak_str:
                bak = Path(bak_str)
                if bak.exists():
                    f.parent.mkdir(parents=True, exist_ok=True)
                    shutil.copy2(bak, f)
                    bak.unlink()
            else:
                if f.exists():
                    f.unlink()
            if f.suffix.lower() in PLUGIN_EXTENSIONS:
                plugins_file.remove(f.name)

        plugins_file.write()
        print(f"✓ Uninstalled: {mod_name}")

    # ── List ─────────────────────────────────────────────────────────────────

    def list_mods(self) -> list[dict]:
        game_slug = self.profile.get("slug")
        manifest = load_manifest()
        plugin_lookup = {p.name: p for p in PluginsFile.read(self.paths.plugins_txt).plugins}
        result = []
        tracked_se_dlls: set[str] = set()
        tracked_plugin_names: set[str] = set()

        data_dir_str = str(self.paths.data_dir)

        for name, entry in manifest.items():
            entry_game = entry.get("game")
            if entry_game is not None and entry_game != game_slug:
                continue
            # Old entries without a game tag: check file paths to avoid
            # showing mods from other games (e.g. Starfield mods in Skyrim).
            if entry_game is None:
                files = entry.get("files", [])
                if files and not any(f.startswith(data_dir_str) for f in files):
                    continue
            files = entry.get("files", [])
            plugins = []
            for f in files:
                ext = Path(f).suffix.lower()
                if ext in PLUGIN_EXTENSIONS:
                    plugins.append(f)
                    tracked_plugin_names.add(Path(f).name)
                elif ext == DLL_EXTENSION:
                    tracked_se_dlls.add(Path(f).name)
            active = all(
                (p := plugin_lookup.get(Path(f).name)) and p.active
                for f in plugins
            ) if plugins else True
            result.append({"name": name, "active": active, "plugins": plugins, "kind": "mod"})

        if self.paths.se_plugins_dir and self.paths.se_plugins_dir.exists():
            for dll in sorted(self.paths.se_plugins_dir.glob(f"*{DLL_EXTENSION}")):
                if dll.name not in tracked_se_dlls:
                    result.append({"name": dll.stem, "active": True, "plugins": [], "kind": "se_plugin"})

        # Plugins present in Plugins.txt but not tracked in the manifest
        # (installed before LSMM or via another tool)
        for p in plugin_lookup.values():
            if p.name not in tracked_plugin_names and (self.paths.data_dir / p.name).exists():
                result.append({
                    "name": p.name,
                    "active": p.active,
                    "plugins": [str(self.paths.data_dir / p.name)],
                    "kind": "unmanaged",
                })

        return result

    # ── Load order ───────────────────────────────────────────────────────────

    def get_load_order(self) -> list[str]:
        return PluginsFile.read(self.paths.plugins_txt).get_order()

    def set_load_order(self, order: list[str]) -> None:
        pf = PluginsFile.read(self.paths.plugins_txt)
        pf.set_order(order)
        pf.write()

    # ── Activation ───────────────────────────────────────────────────────────

    def enable_mod(self, mod_name: str) -> None:
        self._set_mod_active(mod_name, True)

    def disable_mod(self, mod_name: str) -> None:
        self._set_mod_active(mod_name, False)

    def _set_mod_active(self, mod_name: str, active: bool) -> None:
        manifest = load_manifest()
        pf = PluginsFile.read(self.paths.plugins_txt)
        if mod_name not in manifest:
            # Unmanaged plugin: mod_name IS the plugin filename
            pf.set_active(mod_name, active)
            pf.write()
            return
        for f in manifest[mod_name].get("files", []):
            p = Path(f)
            if p.suffix.lower() in PLUGIN_EXTENSIONS:
                pf.set_active(p.name, active)
        pf.write()
        print(f"✓ {'enabled' if active else 'disabled'}: {mod_name}")

    # ── Script extender setup ────────────────────────────────────────────────

    def setup_script_extender(self) -> None:
        se = self.profile.get("script_extender")
        if not se:
            print("No script extender configured for this game.")
            return

        script_path = self.paths.game_root / "se_launch.sh"
        script_path.write_text(
            LAUNCH_SCRIPT_CONTENT.format(
                game_exe=self.profile["game_exe"],
                loader_exe=se["loader_exe"],
            )
        )
        script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC)

        print(f"✓ Launch script created: {script_path}")
        print("\nAdd this to Steam launch options:")
        print(f'  "{script_path}" %command%')
        return script_path

    # ── INI setup ────────────────────────────────────────────────────────────

    def ensure_ini(self) -> None:
        ini = self.paths.custom_ini
        ini.parent.mkdir(parents=True, exist_ok=True)

        content = ini.read_text() if ini.exists() else ""
        if "bInvalidateOlderFiles=1" not in content:
            with ini.open("a") as f:
                f.write("\n[Archive]\nbInvalidateOlderFiles=1\nsResourceDataDirsFinal=\n")
            print(f"✓ Updated: {ini}")
        else:
            print(f"✓ INI already correct: {ini}")
