[Icon Theme]
Name=hicolor
Comment=Fallback icon theme
Hidden=true
Directories=scalable/actions,scalable/mimetypes,16x16/actions,48x48/apps,256x256/apps

[scalable/actions]
Size=16
MinSize=16
MaxSize=512
Context=Actions
Type=Scalable

[scalable/mimetypes]
Size=16
MinSize=16
MaxSize=512
Context=MimeTypes
Type=Scalable

[16x16/actions]
Size=16
Context=Actions
Type=Threshold

[48x48/apps]
Size=48
Context=Applications
Type=Threshold

[256x256/apps]
Size=256
Context=Applications
Type=Threshold
