changelog:
  exclude:
    labels:
      - ignore-for-release
      - chore
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
        - semver-major
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Dependencies
      labels:
        - dependencies
    - title: Other
      labels:
        - "*"
