"""
Bethesda engine plugin — covers Starfield, Skyrim SE, Fallout 4.
Capabilities: load order, script extender, activation toggle.
"""

import shutil
import stat
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from base import BaseEngine
from config import GamePaths
from plugins import PluginsFile
from installer import (
    PLUGIN_EXTENSIONS,
    detect_and_install,
    extract,
    load_manifest,
    record_install,
    remove_from_manifest,
)

LAUNCH_SCRIPT_CONTENT = """\
#!/bin/bash
# Generated by linux-mod-manager
# Replaces the game exe with the script extender loader in Steam's Proton command.
exec "${{@/{game_exe}/{loader_exe}}}"
"""


class BethesdaEngine(BaseEngine):
    has_load_order = True
    has_script_extender = True
    has_activation_toggle = True

    def __init__(self, profile: dict):
        super().__init__(profile)
        self.paths = GamePaths(profile)

    # ── Install ──────────────────────────────────────────────────────────────

    def install(self, archive_path: Path, mod_name: str = None) -> None:
        name = mod_name or archive_path.stem
        tmp = Path(f"/tmp/linuxmm_{name}")
        try:
            print(f"Extracting {archive_path.name}...")
            extract(archive_path, tmp)

            print("Installing files...")
            installed = detect_and_install(tmp, self.paths.data_dir)

            plugins_added = []
            plugins_file = PluginsFile.read(self.paths.plugins_txt)
            for dst in installed:
                if dst.suffix.lower() in PLUGIN_EXTENSIONS and dst.parent == self.paths.data_dir:
                    plugins_file.add(dst.name, active=True)
                    plugins_added.append(dst.name)
            plugins_file.write()

            record_install(name, archive_path, installed)
        finally:
            shutil.rmtree(tmp, ignore_errors=True)

        print(f"✓ Installed: {name}")
        if plugins_added:
            print(f"  Plugins activated: {', '.join(plugins_added)}")

    # ── Uninstall ────────────────────────────────────────────────────────────

    def uninstall(self, mod_name: str) -> None:
        files = remove_from_manifest(mod_name)
        if not files:
            print(f"Not installed: {mod_name}")
            return

        plugins_file = PluginsFile.read(self.paths.plugins_txt)
        for f in files:
            if f.exists():
                f.unlink()
            if f.suffix.lower() in PLUGIN_EXTENSIONS:
                plugins_file.remove(f.name)
        plugins_file.write()

        print(f"✓ Uninstalled: {mod_name}")

    # ── List ─────────────────────────────────────────────────────────────────

    def list_mods(self) -> list[dict]:
        manifest = load_manifest()
        plugin_lookup = {p.name: p for p in PluginsFile.read(self.paths.plugins_txt).plugins}
        result = []
        for name, entry in manifest.items():
            plugins = [
                f for f in entry.get("files", [])
                if Path(f).suffix.lower() in PLUGIN_EXTENSIONS
            ]
            active = all(
                (p := plugin_lookup.get(Path(f).name)) and p.active
                for f in plugins
            ) if plugins else True
            result.append({"name": name, "active": active, "plugins": plugins})
        return result

    # ── Load order ───────────────────────────────────────────────────────────

    def get_load_order(self) -> list[str]:
        return PluginsFile.read(self.paths.plugins_txt).get_order()

    def set_load_order(self, order: list[str]) -> None:
        pf = PluginsFile.read(self.paths.plugins_txt)
        pf.set_order(order)
        pf.write()

    # ── Activation ───────────────────────────────────────────────────────────

    def enable_mod(self, mod_name: str) -> None:
        self._set_mod_active(mod_name, True)

    def disable_mod(self, mod_name: str) -> None:
        self._set_mod_active(mod_name, False)

    def _set_mod_active(self, mod_name: str, active: bool) -> None:
        manifest = load_manifest()
        if mod_name not in manifest:
            print(f"Not installed: {mod_name}")
            return
        pf = PluginsFile.read(self.paths.plugins_txt)
        for f in manifest[mod_name].get("files", []):
            p = Path(f)
            if p.suffix.lower() in PLUGIN_EXTENSIONS:
                pf.set_active(p.name, active)
        pf.write()
        print(f"✓ {'enabled' if active else 'disabled'}: {mod_name}")

    # ── Script extender setup ────────────────────────────────────────────────

    def setup_script_extender(self) -> None:
        se = self.profile.get("script_extender")
        if not se:
            print("No script extender configured for this game.")
            return

        script_path = self.paths.game_root / "se_launch.sh"
        script_path.write_text(
            LAUNCH_SCRIPT_CONTENT.format(
                game_exe=self.profile["game_exe"],
                loader_exe=se["loader_exe"],
            )
        )
        script_path.chmod(script_path.stat().st_mode | stat.S_IEXEC)

        print(f"✓ Launch script created: {script_path}")
        print(f"\nAdd this to Steam launch options:")
        print(f'  "{script_path}" %command%')

    # ── INI setup ────────────────────────────────────────────────────────────

    def ensure_ini(self) -> None:
        ini = self.paths.custom_ini
        ini.parent.mkdir(parents=True, exist_ok=True)

        content = ini.read_text() if ini.exists() else ""
        if "bInvalidateOlderFiles=1" not in content:
            with ini.open("a") as f:
                f.write("\n[Archive]\nbInvalidateOlderFiles=1\nsResourceDataDirsFinal=\n")
            print(f"✓ Updated: {ini}")
        else:
            print(f"✓ INI already correct: {ini}")
